In [1]:
import torch
import torch.nn as nn

In [17]:
torch.manual_seed(42)
inputs=torch.tensor([1.0,2.0,2.0])


In [18]:
neuron=nn.Linear(in_features=3,out_features=1)

In [19]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [20]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [21]:
output=neuron(inputs)

In [22]:
output

tensor([1.6597], grad_fn=<ViewBackward0>)

In [23]:
#verify

neuron.weight @ inputs + neuron.bias

tensor([1.6597], grad_fn=<AddBackward0>)